apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  interval: 10m0s
  url: https://github.com/biomage-org/pipeline
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  interval: 2m0s
  chart: chart-infra/
  valuesFrom:
  - configMapKeyRef:
      name: account-config
      namespace: flux
      key: account-config.yaml
