apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-operator
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups: ["batch", "extensions"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/scale
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cleanup-operator
subjects:
  - kind: ServiceAccount
    name: cleanup-operator